packages:
  - nfs-common

runcmd:
  # NFS
  - mkdir -p /shared
  - echo "${master_ip}:/shared      /shared      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mkdir -p /DATA
  - echo "192.168.73.179:/DATA      /DATA      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mount -a
  # Kubeadm  
  - echo "while [ ! -f /shared/kubeadm-join.bash ]; do sleep 1; done; sudo bash /shared/kubeadm-join.bash" >> /tmp/install.sh
  - su ${admin_user} -c "/tmp/install.sh"
  # authorizing docker
  - su ${admin_user} -c "sudo docker login ${docker_registry} --username ${docker_id} --password ${docker_password}"
  - while [ ! -d /var/lib/kubelet/ ]; do sleep 1; done; 
  - cp /home/${admin_user}/.docker/config.json /var/lib/kubelet/
